### PR TITLE
Make changes to color scheme

### LINKED ISSUE #18: Propose some color schemes and themes for the templates.
Currently we dont have uniform colors throughout the app. Please propose some color schemes.

### PR DESCRIPTION
**Pull request by mrmir**
Fixes #18

### CODE REVIEW

**Comment by mrmir** [comment]
@kvnamipara

**Comment by kvnamipara** [comment]
@mrmir look's great! but it will be great if we made mockups for all pages first. Let me know if you wanna work on that.

**Comment by jainkeval** [comment]
What about this pr??
@kvnamipara @sumedh123

**Comment by sumedh123** [comment]
@kvnamipara @mrmir What has to be done here?

**Comment by kvnamipara** [comment]
@sumedh123 merging is not the issue here, we have to use same color schema for all the pages. 
If anybody is interested in doing that thing then they can go with this.

@mrmir you up for this?

**Comment by mrmir** [comment]
@kvnamipara You mean putting these same colors in all of our pages, yeah? I'll do it! 

Should I open a new issue and then send a PR?

**Pull request closed without merging**
