### PR TITLE
Add style guide

### LINKED ISSUE #13: Add a style guide to write clean code in the repo.

### PR DESCRIPTION
**Pull request by therohitramesh**
Fixes #13

### CODE REVIEW

**Comment by sumedh123** [comment]
@therohitramesh Please claim the issue so that no one else would pick it up too. Also by the style guide I meant something like https://github.com/fossasia/open-event-frontend/blob/development/docs/style-guide.md

**Comment by therohitramesh** [comment]
So it's just a text file? So it doesn't need to be mentioned in package.json also?

**Comment by sumedh123** [comment]
@therohitramesh Correct. It;s just a style guide.

**Comment by sumedh123** [comment]
@therohitramesh Since everyone writes different code. By different code, I mean the indentation, quotes, etc. We need to ensure that the code looks good and the coverage is also good. That's why. Also I will write tests in upcoming days for the same.

**Comment by sumedh123** [comment]
PR not relevant. Closing this.

**Pull request closed without merging**
